services:
  - type: web
    name: my-python-app
    env: docker
    repo: https://github.com/yagneshreddy-somavarapu/Teligram_Ai_Bot.git
    branch: main
    dockerfilePath: Dockerfile
    plan: free
